---
all:
  children:
    linux:
      vars:
        ansible_connection: ssh
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"
        ansible_stderr_callback: null
        # Corrected Indentation below
        secret_path: "lab/linux/{{ inventory_hostname }}"
        ansible_user: "{{ (lookup('community.hashi_vault.vault_kv2_get', secret_path, engine_mount_point='secret')).data.data.username }}"
        ansible_password: "{{ (lookup('community.hashi_vault.vault_kv2_get', secret_path, engine_mount_point='secret')).data.data.password }}"
      hosts:
        mahder05-redhat-rhel10:
        mahder05-ubuntu25-pro:
    windows:
      vars:
        ansible_connection: winrm
        ansible_winrm_port: 5985
        ansible_winrm_transport: basic
        ansible_winrm_scheme: http
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_operation_timeout_sec: 60
        ansible_winrm_read_timeout_sec: 70
        # Dynamic Vault Lookup for Windows
        secret_path: "lab/windows/{{ inventory_hostname }}"
        ansible_user: "{{ (lookup('community.hashi_vault.vault_kv2_get', secret_path, engine_mount_point='secret')).data.data.username }}"
        ansible_password: "{{ (lookup('community.hashi_vault.vault_kv2_get', secret_path, engine_mount_point='secret')).data.data.password }}"
      hosts:
        mahder05-windows11-pro:
    hybrid_lab:
      children:
        linux:
        windows: