---
- name: Verify Vault Connection and Secret Fetch
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Fetch a secret from Vault
      community.hashi_vault.vault_kv2_get:
        engine_mount_point: "secret"
        path: "test" # Path updated to standard KV-v2 format
      register: vault_secret

    - name: Debug Secret
      debug:
        msg: "Vault Connection Successful!"
      when: vault_secret.data.data is defined