---
- name: Windows Host Setup and Management
  hosts: windows
  gather_facts: false

  tasks:
    - name: Dynamically fetch credentials from Vault
      ansible.builtin.include_vars:
        file: ../vars/vault_lookup.yml

    - name: Verify Connectivity to Windows Host
      ansible.windows.win_ping:

    - name: Install Chocolatey packages
      chocolatey.chocolatey.win_chocolatey:
        name:
          - googlechrome
          - notepadplusplus
          - 7zip
          - git
        state: present

    - name: Ensure lab user exists
      ansible.windows.win_user:
        name: "labuser"
        password: "{{ win_vault.data.data.labuser_password | default('M4_Mastery_2026!')
          }}"
        state: present
        groups: ["Administrators"]

    - name: Set timezone to UTC
      ansible.windows.win_timezone:
        timezone: "UTC"

    - name: Write managed banner to Desktop
      ansible.windows.win_copy:
        content: "Managed by Ansible AWX - Lab 2026"
        dest: "C:\\Users\\Public\\Desktop\\managed_by_awx.txt"
