---
- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Remove default site configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: nginx_remove_default_conf | bool
  notify:
    - Restart Nginx

- name: Write Nginx main configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_path }}"
    owner: root
    group: root
    mode: "0644"
    validate: /usr/sbin/nginx -t -c %s
  notify:
    - Restart Nginx

- name: Ensure Nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
